/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package protobuf.serializable;

import java.lang.reflect.Array;
import java.lang.reflect.Field;
import java.util.Map;

import org.junit.Test;

public class LibraryTest {
    void check(Object obj) {
        boolean array = obj.getClass().isArray();

        if (obj instanceof Byte)
            System.out.println("byte");
        if (array) {
            int length = Array.getLength(obj);

            System.out.println("Array:" + length);
            for (int i = 0; i < length; i++) {
                check(Array.get(obj, i));
            }
        }

        else if (obj instanceof Float) {
            System.out.println("Float");
        }
    }

    <T> void getType(Class<T> clz) {
        if(Number.class.isAssignableFrom(clz))
            System.out.println("Long");
    }

    static class MyClzz{
        Map<String, Integer> map;
    }

    @Test
    public void testType() {
        Class<?> clz=MyClzz.class;
        for(Field field : clz.getDeclaredFields()){

        }
    }

    @Test
    public void testSomeLibraryMethod() {
        getType(Map.class);

        byte[] bytes = { 1, 2 };
        check(bytes);
        float x = 1.1f;
        check(x);
    }
}
